services:

  backend:
    build: ./backend

    container_name: myapp

    ports:
      - "5000:5000"

    restart: always


  frontend:

    image: nginx

    container_name: dashboard

    volumes:
      - ./frontend:/usr/share/nginx/html

    ports:
      - "8080:80"

    depends_on:
      - backend

    restart: always