name: CI-CD-Chaos-Recovery

on:
  push:
    branches:
      - main

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify files
        run: |
          pwd
          ls
          ls backend
          ls frontend || true
          ls scripts || true

      - name: Build Docker containers
        run: |
          docker compose build

      - name: Start application
        run: |
          docker compose up -d

      - name: Wait
        run: sleep 10

      - name: Show containers
        run: docker ps